[tool.pylint.'MESSAGES_CONTROL']

# if you do not have applied isort and black previously, uncomment the lines
disable=["consider-using-f-string",
        "unused-variable",
        "unused-argument",
        "invalid-name",
        "simplifiable-if-expression"]

[tool.black]
line-length = 100
target-version = ["py39", "py310"]
skip-string-normalization = true

[tool.isort]
line_length = 100
multi_line_output = 3
length_sort = true